### ISSUE TITLE
Unsafe pointer create exception

### ISSUE THREAD

**Issue by 6rube** [denodrivers/sqlite3#100]
Hi,
i tried to use the newest version of sqlite3 and get this error:

![image](https://user-images.githubusercontent.com/47418292/226871786-2c8e3821-8a6c-4b0e-af59-fd061391ff58.png)

my code looks like this:
```
import { Database } from "https://deno.land/x/sqlite3@0.9.1/mod.ts";

const db = new Database("test.db");

db.close();
```
my runtime args looks like this:
`
deno run -A --unstable test.ts
`

Did i miss something ?

**Comment by DjDeveloperr** [comment]
That's weird.. are you on latest deno version?

**Comment by 6rube** [comment]
Version is up to date. 
![image](https://user-images.githubusercontent.com/47418292/226906907-2d5bb6a8-b076-4f01-b338-e4a168c0bd34.png)

Seems to be a problem with vscode launch.json.
```json
{
    "version": "0.2.0",
    "configurations": [

        {
            "request": "launch",
            "name": "Deno",
            "type": "node",
            "program": "${workspaceFolder}/test.ts",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "C:\\Users\\6rube\\.deno\\bin\\deno.EXE",
            "runtimeArgs": [
                "run",
                "-A",
                "--unstable"
            ],
            "attachSimplePort": 9229
        }
    ]
}
```

**Comment by DjDeveloperr** [comment]
I suspect the --unstable argument is not getting passed correctly, as this error is only reproducible when --unstable is not passed. Either way, seems like it's not a problem in sqlite3 module.
