### ISSUE TITLE
Bug in Reading Integers

### ISSUE THREAD

**Issue by freinberger** [denodrivers/sqlite3#101]
I was trying to store timestamps as INTEGER values in SQLite3, but when reading the values it looks like they are messed up. 

Filtering for the real integer value works (result contains the expected rows). Also when accessing the database via `sqlite3` CLI everything looks okay. Therefore I guess the problem is somewhere in this module.

Please see the screenshot for an example:

<img width="1912" alt="Screenshot 2023-03-29 at 13 20 16" src="https://user-images.githubusercontent.com/126887526/228520220-52b1af7c-38e9-4ecf-b6f4-1ae535aa3aad.png">

Here's the script showing the problem:

```ts
import { Database as SQLite3 } from "https://deno.land/x/sqlite3@0.9.1/mod.ts"

const db = new SQLite3("test.db")

db.exec(`CREATE TABLE IF NOT EXISTS test (
  id TEXT PRIMARY KEY NOT NULL,
  created_at INTEGER NOT NULL
)`)

db.exec(`DELETE FROM test WHERE id = 'test-row' OR id = 'direct';`)

// insert some sample rows

const createdAt = (new Date('2023-03-29T13:04:00+02:00')).valueOf()
console.log({ createdAt })

db.prepare(`INSERT INTO test (id, created_at) VALUES (:id, :createdAt)`).run({
  id: 'test-row',
  createdAt,
})

db.prepare(`INSERT INTO test (id, created_at) VALUES ('direct', 1680087840000)`).run()

// get all rows
const rows = db.prepare(`SELECT * FROM test;`).all()

// log
console.table(rows)
console.table(rows.map(r => ({ id: r.id, createdAt: new Date(r.createdAt) })))

// proofing that SQLite has stored the correct values:
// filtering by exact timestamp
console.log(`Result of:\n   SELECT * FROM test WHERE created_at = 1680087840000;`)
console.table(db.prepare(`SELECT * FROM test WHERE created_at = 1680087840000;`).all())
```

**Comment by DjDeveloperr** [comment]
Set `int64: true` in options to support more than 32-bit integers correctly, however the option comes with little performance penalty. I think we should just make it default to true to avoid confusion.

**Comment by elisee** [comment]
Resurrecting this old issue because I've just hit it.

`node:sqlite` somehow manages to read large numbers correctly, so it might be possible for this module to do the same?
