### ISSUE TITLE
Running in a Web Worker

### ISSUE THREAD

**Issue by alexgleason** [denodrivers/sqlite3#111]
Since this module supports WAL mode and concurrent writes, it makes sense to wrap it in a Web Worker.

**Comment by xyzshantaram** [comment]
I wrote a lib a while ago to make it run in a Web Worker, might help you: https://deno.land/x/worker_sqlite@0.2.3.

**Comment by alexgleason** [comment]
There was another comment here that the author deleted for some reason.

But I wanted to add that I got this working in a web worker and Kysely: https://gitlab.com/soapbox-pub/ditto/-/blob/main/src/workers/sqlite.worker.ts?ref_type=heads

**Comment by DjDeveloperr** [comment]
@alexgleason that's awesome! Just like in your repo, I think this is better done in user land, specific to the way application needs it.

I am not sure what other comment you're talking about. I'm the original author of this module and I didn't delete anything. Even if someone else from the organization deleted, it would show up. Read more here: https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#deleting-a-comment

**Comment by xyzshantaram** [comment]
Guys it was my comment, sorry :sweat_smile: I'd written a lib to do it but forgotten that I'd deprecated it because of some issue. This issue caught my eye so I posted a comment with a link to it, but then realised the lib was deprecated and deleted my comment.

**Comment by alexgleason** [comment]
> Just like in your repo, I think this is better done in user land, specific to the way application needs it.

I agree, I'll close this. Thanks for making this library, it's super helpful! The performance of x/sqlite didn't cut it, so this one is a necessity for me.

**Comment by dustinboston** [comment]
@alexgleason Thanks for posting the link to your solution! I was banging my head against the wall for a day, but you solved the problem! For reference, use Comlink! BTW your code is GREAT.

@DjDeveloperr I have a minimal example extracted from @alexgleason ' s code that I can add to the the doc.md file if you want. Might help some other folks like me.

**Comment by DjDeveloperr** [comment]
@dustinboston that would be a welcome addition!
