### ISSUE TITLE
Allow configuring libsqlite location

### ISSUE THREAD

**Issue by mxcl** [denodrivers/sqlite3#119]
I would like to bundle my own sqlite library, and setting the env variable is not viable. Can I pass it to the Database constructor or another config function?

**Comment by DjDeveloperr** [comment]
Is it viable if you import a module before sqlite3 module is referenced at all that just does `Deno.env.set` to set the custom sqlite library path? Currently we just load the shared library when the module is evaluated, but if it helps we can lazy load it upon creating first instance of Database class.

**Comment by mxcl** [comment]
Yes but that would require my app to have full `--allow-env`. Certainly I can do that for now but it is not my long term preference.

**Comment by mxcl** [comment]
Closing as the design of this library prevents another mechanism.

**Comment by mxcl** [comment]
Certainly would mean I don’t have to vendor and apply my mods every release! I can do the work, just didn’t think it was possible since the import mechanism seemed to be controlled by the deno runtime at module load.
