### ISSUE TITLE
Extensions and Callbacks prevent using this library with macOS bundled dylib

### ISSUE THREAD

**Issue by ianawilson** [denodrivers/sqlite3#121]
I would like to be able to use this library with the sqlite3 dylib that is bundled with macOS (`/usr/lib/sqlite3/libtclsqlite3.dylib`), however it is compiled without the following features:

- Extension loading (https://github.com/denodrivers/sqlite3/pull/83), which requires these optional dylib symbols:
    - `sqlite3_enable_load_extension`
    - `sqlite3_load_extension`
- User defined functions (https://github.com/denodrivers/sqlite3/pull/71), with requires this optional dylib symbol:
    - `sqlite3_step_cb`

I looked into making these symbols optional in the library, but it's a nontrivial lift to have ffi dynamically export symbol functions that are enabled and disabled.

What do you think about supporting this?

**Comment by DjDeveloperr** [comment]
We can set `optional: true` in FFI function definition to do exactly this. The FFI function will become optional as a result in the `symbols` object and we can check for it before calling it.

**Comment by ianawilson** [comment]
That sounds like a great option. I'm new to the FFI APIs, so didn't know about that!

**Comment by DjDeveloperr** [comment]
Fixed this in f638023 - It'll throw a runtime error if these symbols are missing and we attempt to use them now

**Comment by DjDeveloperr** [comment]
0.11.0 is released and should not have this issue! Also, sqlite3_step_cb is not really a symbol but an alias for sqlite3_step, so I did not make it optional as it was not necessary. Let me know how it goes!

**Comment by ianawilson** [comment]
Ok, will do! I am off work for a couple days and will test this on Monday or Tuesday and report back. Thank you!

**Comment by ianawilson** [comment]
I looked into testing this today, but my production environment is on a version of deno that doesn't support jsr, and it looks like this update started using jsr specifiers for it's deps. I'll have to come back to this after we upgrade deno.
