### ISSUE TITLE
How do I update the database?

### ISSUE THREAD

**Issue by guzman109** [denodrivers/sqlite3#127]
Could someone show me how to update a database? I currently have a SQL UPDATE statement in db.exec but I keep getting  this error

error: Uncaught (in promise) SqliteError: 21: SQLite3 API misuse
    throw new SqliteError(code, "SQLite3 API misuse");

**Comment by DjDeveloperr** [comment]
Can you provide a reproduction for this error?

**Comment by guzman109** [comment]
I'm just doing an UPDATE using `db.exec()`. 
`db.exec("UPDATE table SET column=value where id=?", id);`

**Comment by DjDeveloperr** [comment]
<img width="799" alt="image" src="https://github.com/denodrivers/sqlite3/assets/43033058/a5dc1d61-70df-462e-a639-337f9cd5ce96">

Is there anything I'm missing?

**Comment by guzman109** [comment]
Hmm, I wonder if its because I have mine wrapped in a `Promis.all`?

![image](https://github.com/denodrivers/sqlite3/assets/42706936/d3fbb95b-3a8a-44f2-9a9a-ddb80aff803f)

**Comment by DjDeveloperr** [comment]
Promise.all shouldn't be making a difference, it seems like it is failing when calling sqlite3_prepare_v2 which means there is likely something wrong with the query itself, but I don't see it... what if you change all bind parameters to ? instead of using :release_download_count ?

**Comment by guzman109** [comment]
Did not notice that mistake, but that did not work either. Is there anything else I could provide that would help?

**Comment by DjDeveloperr** [comment]
Is it possible for you to reproduce the problem in a small test script instead? We need to isolate the case

**Comment by guzman109** [comment]
@DjDeveloperr Indeed it was a problem with my code. I was using the wrong table. Thank you for your help!

**Comment by DjDeveloperr** [comment]
No problem, glad you found the issue.
