### ISSUE TITLE
Feature request: object parameters

### ISSUE THREAD

**Issue by ashersaupingomez** [denodrivers/sqlite3#15]
Currently, parameters for queries use arrays only. Having objects for parameters would be great as they'd remove the need for parameters into carefully considered order and eliminates the need for repetition in queries which use the same parameter more than once.
Before
```ts
const rows = db.queryObject(`
  SELECT *
  FROM users
  WHERE role = ?
  LIMIT ?
  OFFSET (? * (? - 1));
`, role, postsPerPage, postsPerPage, page);
```
After
```ts
const rows = db.queryObject(`
  SELECT *
  FROM users
  WHERE role = ?
  LIMIT :postsPerPage
  OFFSET (:postsPerPage * (:page - 1));
`, { role, postsPerPage, page });
```

**Comment by DjDeveloperr** [comment]
This is now supported in v0.3.0
