### ISSUE TITLE
Issue with Native libsqlite3.so

### ISSUE THREAD

**Issue by Amatsagu** [denodrivers/sqlite3#30]
That may be mine issue*
- Your code works just fine for windows but I cannot make it working on my ubuntu server. I've installed sqlite3 itself & libsqlite3-0. Library is properly added into bash path, I even  manually added `DENO_SQLITE_PATH` that points to "/lib/x86_64-linux-gnu/libsqlite3.so.0" (default installation path). Still, I got:

```js
May 16 19:48:37 lightcluster deno[2207]: error: Uncaught Error: Native SQLite3 library not found, try installing SQLite3. If you have an existing installation, either add it to path or set the `DENO_SQLITE_PATH` environment variable.
May 16 19:48:37 lightcluster deno[2207]:     const error = new Error(
May 16 19:48:37 lightcluster deno[2207]:                   ^
May 16 19:48:37 lightcluster deno[2207]:     at https://deno.land/x/sqlite3@0.4.2/src/ffi.ts:431:19
May 16 19:48:37 lightcluster deno[2207]: Caused by: Uncaught Error: Could not open library: Could not open library: libsqlite3.so: cannot open shared object file: No such file or directory
May 16 19:48:37 lightcluster deno[2207]:     lib = Deno.dlopen(
May 16 19:48:37 lightcluster deno[2207]:                ^
May 16 19:48:37 lightcluster deno[2207]:     at Object.opSync (deno:core/01_core.js:177:12)
May 16 19:48:37 lightcluster deno[2207]:     at new DynamicLibrary (deno:ext/ffi/00_ffi.js:231:24)
May 16 19:48:37 lightcluster deno[2207]:     at Object.dlopen (deno:ext/ffi/00_ffi.js:329:12)
May 16 19:48:37 lightcluster deno[2207]:     at https://deno.land/x/sqlite3@0.4.2/src/ffi.ts:418:16
```

I'm defeated, all other apps that uses sqlite just works normally.

**Comment by DjDeveloperr** [comment]
It's hard to tell what's the issue here since this module works well on Ubuntu for me. Have you installed libsqlite3-dev?

**Comment by DjDeveloperr** [comment]
So how deno_sqlite3 looks for native library is first it'll look for DENO_SQLITE_PATH env variable for an absolute path to SQLite3 dynamic library (.so), if the variable does not exist it will fallback to loading "libsqlite3.so" based on PATH. Installing libsqlite-dev through apt should put it on PATH AFAIK.

**Comment by DjDeveloperr** [comment]
Closing as stale. Feel free to bump again whenever you can though.
