### ISSUE TITLE
[Deno deploy] Native SQLite3 library not found

### ISSUE THREAD

**Issue by ynwd** [denodrivers/sqlite3#31]
Try to run this code on Deno deploy:

```ts
import { Database } from "https://deno.land/x/sqlite3@0.4.2/mod.ts";

const db = new Database("test.db");

const [version] = db.queryArray("select sqlite_version()")[0];
console.log(version);

db.close();
```

https://dash.deno.com/playground/heavy-mouse-20

and got this error:

```
Error: Native SQLite3 library not found, try installing SQLite3. If you have an existing installation, either add it to path or set the `DENO_SQLITE_PATH` environment variable.
    at https://deno.land/x/sqlite3@0.4.2/src/ffi.ts:401:23
```

**Comment by iuioiua** [comment]
SQLite first requires an operating system for it to be installed on. Deno Deploy doesn't run off an operating system, but instead uses JavaScript isolates. Put simply, SQLite is fundamentally incompatible with Deno Deploy - no workarounds.

If you require SQLite, you'll have to use a server-based solution with another host. If you require Deno Deploy, you'll have to use another network-based database solution.

**Comment by DjDeveloperr** [comment]
Actually the isolated on Deno Deploy also run on an OS but Deno Deploy does not support Deno FFI API for obvious reasons. There is no way to male this module work on Deploy unless FFI API is supported in future.
