### ISSUE TITLE
Does this solve the disadvantages of the x/sqlite library for Deno?

### ISSUE THREAD

**Issue by ralyodio** [denodrivers/sqlite3#37]
# Disadvantages

- Speed: file system IO through Deno can be significantly lower compared to what is achievable using a native binary
- Weaker Persistence Guarantees: due to limitations in Denos file system APIs, SQLite can't acquire file locks or memory map files, which makes some persistence guarantees less strong (e.g. this module can't safely use WAL mode)

https://deno.land/x/sqlite@v2.4.2#comparison-to-plugin-based-modules

**Comment by ralyodio** [comment]
Ok cool. I’ll switch to this one. If issues are being worked on that’s fine.

**Comment by DjDeveloperr** [comment]
SGTM. I hope this answered your questions, closing

**Comment by waynebloss** [comment]
I think this is resolved now with denoland/deno/#14431

**Comment by DjDeveloperr** [comment]
There's some additional optimization work that needs to be done on module's side. #40 does that

**Comment by DjDeveloperr** [comment]
Btw, as an update - this library will very soon receive a rewrite making it fastest (and correct, that is) JavaScript SQLite3 client. Ref #44

**Comment by waynebloss** [comment]
Thanks for the update @DjDeveloperr ! I have been following closely and I am looking forward to trying out the rewrite.
