### ISSUE TITLE
How to run arbitrary statements?

### ISSUE THREAD

**Issue by ralyodio** [denodrivers/sqlite3#39]
`  await db.queryObject("PRAGMA busy_timeout = 30000");`

This doesn't work. How would I run some random SQL statements?

`error: Uncaught SyntaxError: Unexpected reserved word`

`db.queryArray` does same thing.

**Comment by tracker1** [comment]
Try `await db.execute("PRAGMA ...");`

**Comment by DjDeveloperr** [comment]
`SyntaxError` sounds unrelated to library; there must be another error in your code. Also, I notice you're putting await which is unnecessary given this module is sync. I'll close this issue since there's not much to the context that we can help.
