### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by littledivy** [denodrivers/sqlite3#4]
That's it. Same code as in #2

**Comment by littledivy** [comment]
![image](https://user-images.githubusercontent.com/34997667/146642916-87e88861-7712-4876-a284-4a88458b909c.png)

**Comment by DjDeveloperr** [comment]
Trying to fix this in this branch: https://github.com/denodrivers/sqlite3/tree/fix-segfault let me know if it's still seg faulting there.
