### ISSUE TITLE
Invalid FFI pointer type, expected null, integer or BigInt

### ISSUE THREAD

**Issue by xHyroM** [denodrivers/sqlite3#45]
```js
import { Database } from "https://deno.land/x/sqlite3@0.4.4/mod.ts";

const db = new Database("./files/dist/northwind.db");

const a = db.query("SELECT * FROM \"Employees\"");
console.log(a);

db.close();
```

![image](https://user-images.githubusercontent.com/56601352/186760840-0c320e16-2063-4d4c-b484-c971a47d2571.png)

**Comment by waynebloss** [comment]
I am getting this as well with deno `1.2.5`. I thought that upgrading from `sqlite3@0.4.3` to `sqlite3@0.4.4` would fix it, but no.

**Comment by waynebloss** [comment]
There is a whole rewrite going on in #44 so, I'll probably just wait until that's released.

**Comment by DjDeveloperr** [comment]
There was a breaking change in Deno FFI API that split pointer type into two: pointer & buffer. This is fixed in rewrite which will land soon.

**Comment by DjDeveloperr** [comment]
I'll be closing this for now since rewrite has been released and you shouldn't have any issues with it.
