### ISSUE TITLE
No RestBindParameters for 'Statment.get'

### ISSUE THREAD

**Issue by npinochet** [denodrivers/sqlite3#52]
First of all, congratulations on the latest release I'm really liking the new API and functions, it's so clean.

The only problem I have with it, is that according to the `doc.md`, the Statment.get() could be given some params, same as `all` and `values`, but [this doesn't seems to be the case](https://doc.deno.land/https://deno.land/x/sqlite3@0.5.1/mod.ts/~/Statement#get). Is there a reason for this? Or maybe I'm seeing it wrong and this is the expected behavior and didn't understand how `get` works.

Thank you for your time.

**Comment by DjDeveloperr** [comment]
Oh I just forgot to add bind parameters support to `get` 😅 Will add it ASAP

**Comment by DjDeveloperr** [comment]
Fixed in 0.5.2
