### ISSUE TITLE
[uncaught application error]: TypeError - Invalid CString pointer, not valid UTF-8

### ISSUE THREAD

**Issue by ralyodio** [denodrivers/sqlite3#57]
Getting this error all of a sudden.

I wonder if maybe some non-utf8 strings got into my db? I donj't know how to fix.

Here's the query:

```
  .get('/recent', async (context) => {
    const links = await context.state.db
      .prepare(
        'SELECT url, title, excerpt, created_at, count FROM urls ORDER BY created_at DESC LIMIT 50'
      )
      .all();

    context.response.body = links;
  })
```

**Comment by DjDeveloperr** [comment]
Can you provide complete error? Including stack.

**Comment by Blockzilla101** [comment]
having the same issue with running a select query
```js
const storedInfos = db.prepare('SELECT id, uuid FROM PlayerInfo').values<[id: string, uuid: string]>();                                                           
```
```
TypeError: Invalid CString pointer, not valid UTF-8
    at getColumn (https://deno.land/x/sqlite3@v0.5.3/src/statement.ts:72:14)
    at eval (eval at #valuesNoArgs (https://deno.land/x/sqlite3@v0.5.3/src/statement.ts:215:29), <anonymous>:5:54)
    at Statement.#valuesNoArgs [as values] (https://deno.land/x/sqlite3@v0.5.3/src/statement.ts:358:19)
    at updateDatabase (file:///opt/botzilla/src/mindustry/player-info-updater.ts:120:71)
    at file:///opt/botzilla/src/mindustry/player-info-updater.ts:237:5
    at file:///opt/botzilla/src/util/queued-task.ts:17:27
    at Object.action (deno:ext/web/02_timers.js:148:13)
    at handleTimerMacrotask (deno:ext/web/02_timers.js:65:12)
```

**Comment by DjDeveloperr** [comment]
That's pretty weird... I cannot find a way to reproduce this. Does it happen every time or just occasionally?

**Comment by Blockzilla101** [comment]
Well it was fine before but it started happening since yesterday. Seems to be happening every time now.

**Comment by DjDeveloperr** [comment]
Try importing from here https://raw.githubusercontent.com/denodrivers/sqlite3/cstr-fix/mod.ts - should provide some more info about the state in error

**Comment by DjDeveloperr** [comment]
🤔 does the same query work out in SQLite CLI/other libraries? And if possible... could you try to take out some sample data from your DB which can reproduce this problem?

**Comment by Blockzilla101** [comment]
Seems to work fine in the CLI. I'll try to get sample data.

**Comment by Blockzilla101** [comment]
Managed to get it down the row that was causing the issue. Im not really sure how the uuid column managed get that data. [bug.zip](https://github.com/denodrivers/sqlite3/files/9600221/bug.zip)

**Comment by DjDeveloperr** [comment]
Yeah the data in uuid column is corrupted.... shows garbage value in CLI. I have some suspect on the string being freed before use in bind parameters, which would result in this sort of UB.

**Comment by Blockzilla101** [comment]
Unrelated, the library seems to be reading integers incorrectly as well. Not sure if i should make a new issue.

**Comment by DjDeveloperr** [comment]
Oh if those are unix timestamps - they need to be retrieved as 64 bit integers, while we get 32 bit by default because 64 bit integers make up for BigInts and causes pretty significant performance hit. Try setting `db.int64 = true`

**Comment by npinochet** [comment]
Hi, I'm getting this error too from every once in a while with the same symptoms, my database gets corrupted with garbage data and I don't know how could I prevent it.
> Yeah the data in uuid column is corrupted.... shows garbage value in CLI. I have some suspect on the string being freed before use in bind parameters, which would result in this sort of UB.

Could you elaborate on the string being freed before use? Is this a problem with the library bindings? Deno? or SQLite itself?
Thank you for your time and for maintaining this great library

**Comment by DjDeveloperr** [comment]
When passing strings to SQLite, we first encode it to a buffer and pass that to bind function. It is possible that since we do not retain any reference to that buffer _after_ calling bind function, it's getting freed by GC once in a while and when the query is actually run, the data then read from that buffer is corrupted.
To overcome that, I have added some measure to retain references to such things so GC cannot free them. 
@npinochet Would you mind trying the module from https://raw.githubusercontent.com/denodrivers/sqlite3/cstr-fix/mod.ts to see if that fixes the corruption issue? This branch contains that new bind reference code.

**Comment by npinochet** [comment]
Thank you for the quick response! And for taking your time explaining the problem, it now makes sense.
I tried using your fix and it worked! My usual script that populates my DB which caused a corrupted row every time works perfect now.

**Comment by DjDeveloperr** [comment]
Thanks for testing it! I'll land the fix as soon as I get home.
