### ISSUE TITLE
not working inside docker

### ISSUE THREAD

**Issue by jqueryisamonad** [denodrivers/sqlite3#64]
**Dockerfile**
```Dockerfile
FROM denoland/deno:1.26.2
WORKDIR /app
ADD . .
RUN deno cache main.ts
CMD ["run", "-A", "--unstable", "main.ts"]
```

**main.ts**
```ts
import * as sqlite from "https://deno.land/x/sqlite3@0.6.1/mod.ts";

const db = new sqlite.Database("test.db");

const [version] = db.prepare("select sqlite_version()").value<[string]>()!;
console.log(version);

db.close();
```

**docker build and run (failed silently without any error)**
<img width="791" alt="image" src="https://user-images.githubusercontent.com/23063254/198321146-ea9d5f3a-01bb-4ad7-981d-ae03aacdd337.png">

**Comment by tracker1** [comment]
This may well not work, but possibly worth a try...

Create an `init.ts` that creates an instance of `:memory:` and run it during build, just to make sure the `libsqlite3.so` is downloaded?  Could also try installing the system library (apt?) etc.

**Comment by exe-dealer** [comment]
deno v1.26.2 is broken, use v1.27.0 (or v1.26.1)

**Comment by DjDeveloperr** [comment]
Is this still an issue?

**Comment by DjDeveloperr** [comment]
Seems like its not.
