### ISSUE TITLE
Support user-defined functions

### ISSUE THREAD

**Issue by spiffytech** [denodrivers/sqlite3#68]
SQLite's regex syntax [errors out](https://www.sqlite.org/lang_expr.html#regexp) unless a user-defined regex function is defined.

User-defined functions are also useful for compensating for SQLite's poor datetime logic.

They can also be used with triggers to mimic Postgres' `LISTEN`/`NOTIFY` behavior.

I'd expect an implementation to resemble `better-sqlite3`'s [support for user-defined functions](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#functionname-options-function---this).

**Comment by DjDeveloperr** [comment]
These aren’t possible to implement without making queries terribly slow because they won’t be able to take fastpath anymore if callback support is enabled.

**Comment by spiffytech** [comment]
Does that perf hit happen only when calling a user-defined function, or does it happen for all queries?

**Comment by DjDeveloperr** [comment]
Hmm, it is actually possible to make the query take different path if it calls a user defined function. It's just matter of identifying if the query accesses it or not (which I believe is not possible to identify via any SQLite C API). We could make it opt-in to enable callback support (calling user defined functions without it will be undefined behavior; when call is through fast path v8 will crash). That could be either per-statement or just a Database option. Per statement seems more practical though. What do you think?

cc @littledivy
