### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by ashersaupingomez** [denodrivers/sqlite3#8]
Hi there, I'm wanting to make queries with dynamic parameters but cannot find any documentation regarding it. Is this simply something that hasn't been done yet?

PS. So far, this is looking like a very quality library. I'm very keen to see what it evolves into :)

**Comment by DjDeveloperr** [comment]
You can bind parameters to a query using the variadic arguments in `queryArray`/`queryObject` methods.
See: https://doc.deno.land/https://deno.land/x/sqlite3@0.2.3/mod.ts/~/Database#queryArray (the `...args` parameter).
For example:
```ts
db.queryArray<[string]>("select name from users where id = ?", id);
```

**Comment by ashersaupingomez** [comment]
Thanks for the new documentation!

I've attempted using `.queryArray` and `.queryObject` multiple times without and get empty results. My database is very simple and essentially lines up to the example you just added to the documentation for binding parameters. I've triple-checked my stuff and can't see what could be wrong. I've retried the same command in the CLI and do get results.

I ran `deno test` on your module and everything passes, including binding parameters. I don't know what the issue could be.

Deno version: 1.17.1 (release, x86_64-apple-darwin)
Module version: 0.2.3
macOS version: 12.1
SQLite version: 3.37.0

**Comment by DjDeveloperr** [comment]
Could you provide a small reproduction for this case?

**Comment by ashersaupingomez** [comment]
I tried your the same code that for the users table and it worked fine. However, I'm still having issues with my database not showing any results. Here's the exact SQL and code I use.
```
import { Database } from "https://raw.githubusercontent.com/denodrivers/sqlite3/main/mod.ts";

const db = new Database("test");

db.execute("CREATE TABLE authors (author_name TEXT NOT NULL, author_username TEXT NOT NULL UNIQUE, author_bio TEXT, PRIMARY KEY (author_username));");
db.execute(`INSERT INTO authors(author_name, author_username, author_bio) VALUES ('John Doe', 'john_doe', "I'm John Doe.");`);

console.log(db.queryArray("SELECT * FROM authors"));
console.log(db.queryArray("SELECT * FROM authors WHERE author_username = ?", "john_doe"))

db.close();
```
Result:
```
> [ [ "John Doe", "john_doe", "I'm John Doe." ] ]
> []
```

**Comment by DjDeveloperr** [comment]
Ah, it seems that string parameters are failing here. I will look into this right now.

**Comment by DjDeveloperr** [comment]
Found the problem. It was because the C string's null byte was being included in bind parameter. I'll land fix and make a patch release ASAP

**Comment by ashersaupingomez** [comment]
Beautiful!

**Comment by DjDeveloperr** [comment]
Tagged 0.2.4 with the fix

**Comment by ashersaupingomez** [comment]
It works! Thank you 🙏🏾
