### ISSUE TITLE
TS Error when running the vendored code

### ISSUE THREAD

**Issue by milaz** [denodrivers/sqlite3#85]
When running the vendored version of the code that uses this library, the user will get a TypeScript error described here:
https://github.com/denosaurs/plug/issues/23

The issue was fixed in `plug@1.0.1`. Could you consider upgrading the dependency, please?

**Comment by DjDeveloperr** [comment]
Will be fixed by #81

**Comment by DjDeveloperr** [comment]
PR is merged, I'll cut new release as soon as I'm on PC
