### ISSUE TITLE
Use tagged releases of SQLite

### ISSUE THREAD

**Issue by eliassjogreen** [denodrivers/sqlite3#91]
Currently the git submodule of sqlite not up to date nor using a tagged release. We should probably update to the latest `version-3.40.1`, and try to keep up with new tags as they are released.

**Comment by eliassjogreen** [comment]
@DjDeveloperr There has now been a 3.41 release, I wonder if it might make sense to have a daily cron-job action which checks if there has been a new release and if so builds and releases a new patch ([or even as semver metadata, that way we keep our semver version an their version separate](https://semver.org/#spec-item-10))?

**Comment by tracker1** [comment]
As much as I appreciate knowing the defacto library version used... I find combined semver like above kind of icky... also, wouldn't it be `-` not `+`?

Aside: would probably try to keep the bump to semver part... if the minor was bumped, then bump minor here, if patch, bump patch...  Assuming sqlite library is also following semver.

**Comment by eliassjogreen** [comment]
[SQLite does indeed now use semver](https://www.sqlite.org/versionnumbers.html) but I can agree it is somewhat ugly combining our and their versions into one. It would be using the `+` separator as the `-` separator is used for pre-releases, which this is not. I guess another option would be to release a pure `x.y.z` semver version for all of our actual releases, and then provide the `+s.q.l` versions as a separate, optional version and always up to date version for those who want to pin the sqlite version used.
