### ISSUE TITLE
Open database readOnly not working

### ISSUE THREAD

**Issue by leonardoanalista** [denodrivers/sqlite3#93]
Hi there 

I am trying to open the database in `readOnly` mode but it's not working.

My code: 
```
const db = new Database("myfile.db", { readonly: true });
```

result: 
```
error: Uncaught (in promise) SqliteError: 21: SQLite3 API misuse
    throw new SqliteError(code, "SQLite3 API misuse");
          ^
    at unwrap (https://deno.land/x/sqlite3@0.8.0/src/util.ts:36:11)
    at new Database (https://deno.land/x/sqlite3@0.8.0/src/database.ts:221:5)
```

V: 0.8.0

Thanks,

**Comment by DjDeveloperr** [comment]
Thanks for reporting, I'll cut new patch release 0.8.2 for fixing this bug.

**Comment by leonardoanalista** [comment]
Thanks. Is there any performance benefit to flag that we are opening for readonly? Just curious about it.

**Comment by DjDeveloperr** [comment]
There most likely is some performance benefit, for example if DB is opened as read-only, we can set journal mode to off since no changes can be made to data.
