### ISSUE TITLE
Fts5

### ISSUE THREAD

**Issue by 6rube** [denodrivers/sqlite3#94]
Hi, I am looking for an sqlite module with fts support. This module looks pretty good, but I could not find any information about fts. As far as I know fts is a standard feature from sqlite which you have to enable threw command arguments. How do I enable the extension in this case?

**Comment by DjDeveloperr** [comment]
Currently, there is no out of the box support for FTS5. However, it is possible to either:

a. Build sqlite3 yourself with the flag to enable FTS5 and point to it using `DENO_SQLITE_PATH` env variable.
b. Build the FTS5 extension and load it using `db.loadExtension`.

For building both of the above, instructions are here: https://www.sqlite.org/fts5.html

However, I'll look into enabling FTS5 support in the main builds right now.

**Comment by DjDeveloperr** [comment]
FTS5 is now available out of the box from 0.9.0 :)
